### ISSUE TITLE
Cannot get this plugin to work

### ISSUE THREAD

**Issue by danspam** [tom-haines/branch-window-title#5]
I have tried with Rider and PhpStorm opening different projects using git source control and each time I get the debug log message 'No git repository found'. What could I be doing wrong?

**Comment by tom-haines** [comment]
I have pushed an updated version (0.5.5) that will give you better log output about what paths IntelliJ provided to search.  If the project dir(s) do not contain a ".git/HEAD" file, or you have not enabled the VCS plugin (defaults on), either could be root cause.  It may take a few days for IntelliJ to approve through their plugin store.  Pls re-open once you have a look at the updated log output and/or have reproducible case.  It should work with zero config, other than opening a project that has a .git folder in the structure.

See
https://github.com/tom-haines/branch-window-title/pull/6/files

**Comment by danspam** [comment]
Managed to build your changes and install from the file

For Rider I now get:

_No git repository found in search path: [C:/Users/Dan/.nuget/packages/microsoft.net.test.sdk/16.4.0/build/netcoreapp2.1]_

So for Rider, the method of getting the current project directory seems to be returning a path to one of the dependency packages instead.

For PhpStorm I now get (adjusted for privacy)

_No git repository found in search path: [D:/path/to/project]_

This is correct. However, my git directory is not in the project path, but several directories higher, which would match up to your statement regarding where the git directory needs to be.

Apologies - I have no experience with java and IDEA, so any chance of me contributing to this is close to nil!

**Comment by tom-haines** [comment]
@danspam 
I don’t think the plugin will do what you want for your use case.  You could test plugin works as expected by opening a project that has a git repository within the project tree, in which case it should detect that repo, and modify the window title accordingly.

The plugin is dependent on the open project having a git repository somewhere within its scope.  It's likely the plugin will only work if a git repository is located within the open project directory tree (but not in directories that are higher than the open project's scope) - unless IntelliJ "guesses" (wording of API) the project has a higher base directory.

I think from privacy point of view, the plugin shouldn’t reach outside the confides of the scope of the project that IntelliJ was asked to open (my view only).

**Comment by danspam** [comment]
@tom-haines 
I understand why it does not work on PhpStorm for that particular project as the location of the git folder is somewhat unusual. It is working fine in PhpStorm.

However, for Rider, the folder it is searching in is completely wrong (sorry, I did not explain that in my previous comment!) - it is way outside the project folder. The folder it is searching is in fact a cache folder for the .Net package manager and nothing to do with the project I had open.

**Comment by tom-haines** [comment]
It does sound strange re Rider.  The plugin relies on this method of the IntelliJ SDK as to determining the project directory:

```kotlin
/**
 *  Tries to guess the "main project directory" of the project.
 *
 *  There is no strict definition of what is a project directory, since a project can contain multiple modules located in different places,
 *  and the `.idea` directory can be located elsewhere (making the popular [Project.getBaseDir] method not applicable to get the "project
 *  directory"). This method should be preferred, although it can't provide perfect accuracy either.
 *
 *  @throws IllegalStateException if called on the default project, since there is no sense in "project dir" in that case.
 */
fun Project.guessProjectDir() : VirtualFile? {
  val modules = ModuleManager.getInstance(this).modules
  val module = if (modules.size == 1) modules.first() else modules.find { it.name == this.name }
  module?.rootManager?.contentRoots?.firstOrNull()?.let {
    return it
  }
  return LocalFileSystem.getInstance().findFileByPath(basePath!!)
}
```

For whatever reason in the case of your project, the IntelliJ SDK function is "guessing" the project directory incorrectly.  

To be fair, they state that `the method should be preferred`, although `it can't provide perfect accuracy either`.
